#!/usr/bin/env python3
"""시즌 4 여름 + 막간극 2~4 삽화. out/v06u/<id>_0.png  사용: shots_summer.py [bg|scenes|all|id,...]"""
import subprocess, sys, os, time
SC=os.path.dirname(os.path.abspath(__file__)); A="/home/user/somsom-city/assets/"; AD=A+"day/"; OUT=f"{SC}/out/v06u"; os.makedirs(OUT,exist_ok=True)
PRO,FLASH="gemini-3-pro-image","gemini-3.1-flash-image"; LINE=A+"01_group_lineup.png"
STYLE=("The first reference images are CHARACTER MODEL SHEETS. Every character must match its model sheet EXACTLY: same proportions, face rules, clothes and colors. "
 "The second-to-last reference image is the GROUP LINEUP showing correct relative heights, and the last reference image is the background/style guide: thin uniform dark outlines, flat matte colors, no shading, no gradients, muted pastel palette. "
 "Rules: eyes are small white circles with a black dot pupil always visible; Kkito has NO nose, ears the same pink as the face with only a small light-pink oval at each ear TIP, two tiny curly strands on the forehead; "
 "Migae stands on its rear four legs like a small dog and holds its two front legs up as short arms at the chest, pink bow on the head. Nobody wears glasses except Bookgeo (square black) and Grandma (round gold, on top of her head). No cats, no dogs, no extra animals of any kind. "
 "HEIGHT RULE, measured against Kkito's full height: Boneul 110% (the tallest), Kkito 100%, Ramda's head reaches Kkito's mid-chest (67%), Grandma Lachilchin's head reaches Kkito's hip (57%), Bookgeo on four legs reaches Kkito's knee (47%), Migae reaches just below Kkito's knee (41%) — Migae is never taller than Kkito's knee. "
 "SPECIES: Ramda is a red-brown SQUIRREL with a big bushy upright tail (about as tall as her torso, never larger than her body), never a cat. Grandma Lachilchin is a grey CHINCHILLA: small, round, very fluffy, big round ears, short blunt muzzle, never a cat or dog. Bookgeo is a tortoise with a SHORT THICK neck, never long or giraffe-like, and there is only ever ONE tortoise in a picture. Kkito's two long ears stand straight UP unless she is lying down. Boneul has long sloth arms that must be visible. "
 "The lineup image is ONLY a height reference: draw ONLY the characters named in the scene, each exactly once. "
 "Everyone wears their usual clothes. Vertical 3:4 composition, characters large enough to read their faces, no text, no letters, no watermark.")
KK,MG,BN,RM,BG,LC=("Kkito (pink rabbit, model sheet)","Migae (black pet ant, model sheet)","Boneul (grey sloth, model sheet)","Ramda (squirrel, model sheet)","Bookgeo (tortoise on four legs, model sheet)","Grandma Lachilchin (chinchilla, model sheet)")
B={k:f"{SC}/refs/board_{k}.jpg" for k in ["kkito","migae","boneul","ramda","bookgeo","lachilchin"]}
def bg(name):
    m={"alley_su":AD+"bg_alley_summer.jpg","alley_ht":AD+"bg_alley_heat.jpg","alley_n":AD+"bg_alley_night.jpg","alley_r":AD+"bg_alley_rain.jpg","entry_su":AD+"bg_day_entry_summer.jpg","entry_ht":AD+"bg_day_entry_heat.jpg","entry_n":AD+"bg_day_entry_night.jpg","entry_r":AD+"bg_day_entry_rain.jpg",
       "alley_sp":AD+"bg_alley_spring.jpg","alley_w":AD+"bg_alley_winter.jpg","fest":f"{OUT}/u_fest_bg_0.png"}
    return m.get(name, A+name)
SHOTS=[]; BGS=[]
def scene(id,model,chars,bgname,text,season=""):
    refs=[B[c] for c in chars]+[LINE,bg(bgname)]
    extra=" Bookgeo walks on four legs and always wears his square black glasses; when he holds something he uses exactly ONE arm from under the front of his shell while all four legs stay on the ground." if "bookgeo" in chars else ""
    SHOTS.append((id,model,refs,STYLE+extra+season+"\n\nScene: "+text))
SU=" SUMMER: strong sunlight, deep flat shadows, cicada-season feel."
def recolor(id,src,text):
    BGS.append((id,FLASH,[src],"Recolor and re-dress this EXACT illustration: "+text+" Keep every line, object and the composition identical; change only colors, foliage, sky, weather and small seasonal props. Same flat matte style, thin outlines, no text."))
recolor("bg_alley_summer",A+"bg_alley.png","early summer: the trees are full of deep green leaves, bright blue sky, strong sunlight with a few flat dark shadow shapes on the ground, a small electric fan visible in one window, everything fresh and green.")
recolor("bg_alley_heat",A+"bg_alley.png","peak summer heat wave: very bright washed-out sunlight, pale hot sky, deep dark flat shadows under the trees, heat shimmer implied only by a paler ground, a hand fan lying on the bench, leaves a slightly dusty green.")
recolor("bg_day_entry_summer",A+"bg_day_entry.png","early summer seen through the door/window: deep green leaves, bright blue sky, strong sun, a small electric fan on the floor by the door.")
recolor("bg_day_entry_heat",A+"bg_day_entry.png","heat wave outside: very bright pale sky, washed-out sunlight, deep shadows, a hand fan on the shoe cabinet, a glass of water with ice by the door.")
BGS.append(("u_fest_bg",PRO,[AD+"bg_alley_night.jpg"],"Draw a NEW illustration in EXACTLY the same flat matte style, thin uniform dark outlines and muted pastel night palette as this reference alley: the flat rooftop of a small beige apartment building at night, seen from the back of the rooftop; twelve simple folding chairs in rows facing a large white cloth screen hung on a laundry line between two poles, a small old film projector on a crate at the back, a string of small round lights, a low railing, potted tomato plants in one corner, the dark alley and a second rooftop visible beyond the railing, a starry night sky. No people, no animals, no text."))
# ---- 아침 ----
scene("u_a_water",FLASH,["kkito","migae"],"entry_su",f"early summer morning in front of apartment 901: a small flower bed with tomato plants and one red cherry tomato. {KK} waters it with a watering can, ears up, squinting in the sun. {MG} walks under the falling water with its antennae up.",SU)
scene("u_a_market",FLASH,["kkito","migae"],"bg_day_market.png",f"summer market day in the alley: stalls with awnings making shade, watermelons, paper fans, a block of ice on one table. {KK} walks in the shade of an awning fanning herself with a paper fan, ears drooping from heat. {MG} sits on the ice block.",SU)
scene("u_a_fan",FLASH,["kkito","migae","lachilchin"],"entry_su",f"a hot apartment stairwell. {LC}, short and round, comes down the stairs fanning herself with a round paper fan, glasses on her head. {KK} at the bottom holding a boxed electric fan, looking up. {MG} on a step beside Kkito.",SU)
scene("u_a_snack",FLASH,["kkito","migae","lachilchin"],"entry_su",f"morning at the open front door of apartment 901. {LC}, short and round, holds up a tray with two tall glasses of a pale grain drink with ice, condensation drops on the glass, smiling with crescent eyes. {KK} in the doorway, ears up, happy. {MG} reaching for an ice cube.",SU)
scene("u_a_roof",FLASH,["kkito","ramda","bookgeo","migae"],"alley_su",f"a flat rooftop with a low railing in early summer, the green alley below. {RM} sweeps the rooftop with a broom, tail high. {BG} on four legs has just arrived at the top of the stairs, glasses on, resting. {KK} carries a folding chair. {MG} rides on Bookgeo's shell.",SU)
# ---- 낮 변형 ----
scene("u_v_bkshade",FLASH,["kkito","bookgeo","migae"],"bg_day_perfume_atelier.png",f"the shaded spot in front of the perfume atelier in summer heat. {BG} on four legs sits very still, his shell wet with water drops, glasses on, eyes half closed. {KK} sits beside him in the shade with her knees up, ears drooping. {MG} lies flat in the shade under the edge of Bookgeo's shell.",SU)
scene("u_v_fan",FLASH,["kkito","ramda","migae"],"bg_day_acorn_shop.png",f"inside the vintage shop in summer, a small electric fan turning on the counter. {RM} sits in front of the fan polishing a button, her fur and tail blown by the wind, looking out the window. {KK} sits opposite with her ears blown back by the fan. {MG} in front of the fan with antennae streaming back.",SU)
scene("u_v_tomato",FLASH,["kkito","boneul","migae"],"bg_day_bamboo_entry.png",f"the entrance stairs of Bamboo Grove Villa in summer. {BN}, tallest, slowly comes down the stairs carrying a basket of cherry tomatoes; several tomatoes have fallen one on each step. {KK} picks one up from a step, ears up. {MG} holds one tomato bigger than its head.",SU)
scene("u_v_ice",FLASH,["kkito","lachilchin","migae"],"bg_day_grandma_room.png",f"Grandma's small kitchen in summer, the window open showing a rooftop across the alley. {LC}, short and round, breaks a block of ice with an ice pick, glasses on her head. {KK} holds a bowl to catch the pieces. {MG} hugs an ice cube on the counter.",SU)
scene("u_v_chairs",FLASH,["kkito","ramda","boneul","migae"],"alley_su",f"a flat rooftop with a low railing, early summer. {RM} carries a folding chair, tail high. {BN}, tallest, slowly carries a potted tomato plant. {KK} carries two chairs, ears up. {MG} sits on an already placed chair.",SU)
scene("u_walk_shade",FLASH,["kkito","migae"],"alley_ht",f"the alley in strong summer heat, deep flat shadows under the trees. {KK} walks only inside the shadow, holding a pink leash, ears drooping, a paper fan in her other hand. {MG} at the end of the leash in four tiny pink boots, also carefully staying inside the shadow.",SU)
# ---- 저녁 ----
scene("u_n_tomato",FLASH,["kkito","migae"],"entry_su",f"evening, the small flower bed by the villa steps: one bright red cherry tomato on the plant, orange dusk light. {KK} crouches looking at it with her hands on her knees, ears soft, not picking it. {MG} sits guarding it.",SU)
scene("u_n_shade",FLASH,["kkito","migae"],"bg_day_acorn_shop.png",f"evening outside the vintage shop, warm light inside, a small blank chalkboard by the door in the shade. {KK} stands reading it with a small smile. {MG} lies in the strip of shade under the chalkboard.",SU)
scene("u_n_fan",FLASH,["kkito","migae","lachilchin"],"entry_su",f"evening in an apartment corridor, a standing electric fan at the end of the hall. {LC}, short and round, sits on a small stool in front of the fan with her eyes closed, fur blowing, glasses on her head. {KK} peeks from the stairs, smiling. {MG} walks past the fan with antennae streaming.",SU)
scene("u_n_cup",FLASH,["kkito","migae"],"entry_su",f"evening, the doormat of apartment 901. A clean glass with two ice cubes placed back on it. {KK} crouches in the doorway looking at it, ears soft. {MG} sits beside the glass, antennae in a heart shape.",SU)
scene("u_n_roof",FLASH,["kkito","migae"],"alley_su",f"a flat rooftop with twelve folding chairs in rows at sunset, the alley below, a second rooftop across, orange and pink sky. {KK} stands at the railing looking at the sunset, ears relaxed. {MG} sits on the railing beside her.",SU)
scene("u_n_nap",FLASH,["kkito","migae"],"bg_day_studio.png",f"summer Sunday evening in apartment 901, a standing fan turning. {KK} asleep on the floor in front of the fan, ears blown sideways. {MG} asleep on her stomach, antennae blown sideways too.",SU)
# ---- 두 반장 줄기 ----
scene("u_meet",FLASH,["kkito","ramda","boneul","migae"],"entry_su",f"morning at the open front door of apartment 901. {RM} holds up an official poster with both hands, tail high, excited. Behind her {BN}, tallest, stands with his hands in his pockets, deadpan. {KK} in the doorway looks from one to the other, ears up. {MG} between Ramda and Boneul.",SU)
scene("u_meet_n",FLASH,["kkito","migae"],"entry_su",f"evening, a villa notice board with one blank poster pinned in the middle. {KK} stands in front of it with her arms crossed, ears soft, a small smile. {MG} looks up at the poster.",SU)
scene("u_bon_meeting",FLASH,["kkito","boneul","migae"],"bg_day_boneul_home.png",f"Boneul's living room in summer, a fan turning. {BN}, tallest, sits on the sofa with an open blank notebook on his knees and a pen, deadpan. {KK} sits stiffly at the far end of the sofa with her hands on her knees, ears straight up. {MG} on the table between them with a bag of chips.",SU)
scene("u_mem1",FLASH,["kkito","boneul","migae"],"alley_n",f"a memory at night: a small trash collection corner at the end of the alley with a few bins, one street lamp. {KK} and {BN}, tallest, each hold a handle of the SAME large plastic kimchi container between them, both frozen, staring at each other in surprise, Kkito's ears straight up. {MG} peeks from behind a bin. Slightly faded, soft colors like a memory.")
scene("u_mem2",FLASH,["kkito","boneul","migae"],"bg_day_cityhall.png",f"a memory: a small meeting room with a table and simple chairs. {KK} and {BN}, tallest, sit at opposite ends of the table, both with their hands firmly in their laps, NOT raising their hands, looking away from each other. {MG} under the table. Slightly faded, soft colors like a memory.")
scene("u_mem3",FLASH,["kkito","boneul","lachilchin","migae"],"bg_day_grandma_room.png",f"a memory in Grandma's living room: {LC}, short and round, holds two identical plates of green rice cakes, one in each hand, smiling with crescent eyes. On her left {KK} reaches for one plate, on her right {BN}, tallest, reaches for the other; they do not see each other. {MG} between them. Slightly faded, soft colors like a memory.")
scene("u_lam_projector",FLASH,["kkito","ramda","migae"],"bg_day_acorn_shop.png",f"the back storeroom of the vintage shop. {RM} has pulled a cloth off an old dusty film projector with two reels sitting on a crate, holding the cloth, eyes shining. {KK} crouches beside it looking at the lens, ears up. {MG} touches the reel with its antenna.",SU)
scene("u_bon_screen",FLASH,["kkito","boneul","migae"],"bg_day_bamboo_entry.png",f"a rooftop with a laundry line between two poles, potted tomato plants; a big white cloth hangs from the line billowing in the wind. {BN}, tallest, pins one corner slowly. {KK} holds the other corner, the cloth blowing over her ears. {MG} sits under the cloth in its shade.",SU)
scene("u_permit",FLASH,["kkito","ramda","migae"],"bg_day_cityhall.png",f"the city hall service counter in summer, a fan on the counter. {RM} stands holding papers, looking up at Kkito with an expectant smile, tail up. {KK} stands at the counter with her hand raised slightly, mouth open, ears up, calmer than before. {MG} on the counter. No staff visible.",SU)
scene("u_permit_n",FLASH,["kkito","migae"],"entry_su",f"evening, a villa notice board: a blank certificate with two round red stamps pinned in the middle. {KK} presses the last pushpin in, smiling, ears up. {MG} on the floor holding a spare pushpin.",SU)
scene("u_gm_plates",FLASH,["kkito","lachilchin","migae"],"bg_day_grandma_room.png",f"Grandma's kitchen in summer. {LC}, short and round, sets two identical plates of green rice cakes side by side on the table, glasses on her head, gentle smile. {KK} stares at the two plates with her ears straight up, surprised. {MG} between the plates.",SU)
scene("u_bon_film",FLASH,["kkito","boneul","migae"],"bg_day_boneul_home.png",f"Boneul's living room. {BN}, tallest, lies on the sofa holding a remote control, deadpan. {KK} sits on the floor beside the sofa holding a small hand-drawn picture book with a blank cover, ears up, hesitant. {MG} on the sofa arm.",SU)
scene("u_lam_mc",FLASH,["kkito","ramda","migae"],"bg_day_acorn_shop.png",f"inside the vintage shop. {RM} writes on a blank sheet of paper on the counter with a marker, tongue out in concentration, tail up. {KK} stands beside her pointing at the paper. {MG} sits on the counter holding a spare marker.",SU)
scene("u_eve",PRO,["kkito","boneul","migae"],"alley_n",f"night before the festival on a small rooftop: a white cloth screen on a laundry line glowing with a plain rectangle of projector light, folding chairs, a string of small lights, the dark alley below. {KK} and {BN}, tallest, sit side by side on two chairs facing the screen, seen from behind at an angle so both faces are partly visible; Kkito's ears up, Boneul deadpan. {MG} sits on the ground between their chairs.")
scene("u_eve_told",PRO,["kkito","boneul","migae"],"alley_n",f"night on the rooftop, the white screen glowing behind them. {KK} and {BN}, tallest, sit side by side on folding chairs, both turned toward each other and laughing, Kkito with her eyes crescent and ears up, Boneul with a rare wide smile. {MG} between them with antennae in a heart shape.")
scene("u_eve_quiet",FLASH,["kkito","boneul","migae"],"alley_n",f"night on the rooftop, the white screen glowing. {KK} and {BN}, tallest, sit side by side on folding chairs quietly looking at the screen, seen from behind, a small gap between the chairs. {MG} sits on the ground between them looking at the screen too.")
scene("u_eve_n",FLASH,["kkito","migae"],"bg_day_studio.png",f"night in apartment 901, the window open; outside and above, a white cloth screen on a rooftop billows in the night wind against the dark sky. {KK} sits on the windowsill hugging her knees looking up at it, ears relaxed. {MG} on the sill beside her.")
scene("u_book",FLASH,["kkito","migae"],"bg_day_studio.png",f"apartment 901 desk in summer, a fan turning. {KK} sits at the desk drawing in a large open sketchbook with crayons, tongue out, ears up. {MG} sits on the desk with one foot on the page leaving a tiny footprint. The pages are blank.",SU)
scene("u_book_fall",FLASH,["kkito","migae"],"bg_day_studio.png",f"a close view of a desk: an open sketchbook page showing a simple crayon drawing of the ginkgo alley with strings of light bulbs and tiny simple figures (no readable details, no text). {KK}'s hands hold a crayon at the page edge; her face leans in from the side, ears up. {MG} sits at the page corner.",SU)
scene("u_book_winter",FLASH,["kkito","migae"],"bg_day_studio.png",f"a close view of a desk: an open sketchbook page showing a simple crayon drawing of a snowy alley with round paper lanterns (no text). {KK}'s hands hold a crayon at the page edge; her face leans in from the side, ears up. {MG} sits at the page corner.",SU)
scene("u_book_spring",FLASH,["kkito","migae"],"bg_day_studio.png",f"a close view of a desk: an open sketchbook page showing a simple crayon drawing of a flea market with striped awnings and pink blossoms (no text). {KK}'s hands hold a crayon at the page edge; her face leans in from the side, ears up. {MG} sits at the page corner.",SU)
scene("u_letter_ed",FLASH,["kkito","migae"],"entry_su",f"morning, apartment 901 doorway, the mailbox open. {KK} reads a letter with both hands, ears up, a small proud smile. {MG} holds the envelope.",SU)
# ---- 미개 ----
scene("u_mg_rain",FLASH,["kkito","migae"],"entry_r",f"the open front door of apartment 901, heavy summer rain outside, the alley like a shallow river. {MG} stands right at the threshold catching a raindrop on its antenna, looking back over its shoulder at Kkito. {KK} crouches behind it in the doorway holding four tiny pink boots.")
scene("u_mg_hot",FLASH,["kkito","migae"],"bg_day_studio.png",f"apartment 901 in blazing summer light. {MG} lies flat on the floor beside an untouched plain food bowl, antennae lying flat on the floor, eyes half closed. {KK} kneels beside it fanning it with a paper fan with one hand and holding an ice cube in the other, ears down with worry.",SU)
scene("u_mg_cool",FLASH,["kkito","bookgeo","migae"],"bg_day_perfume_atelier.png",f"the shaded spot in front of the perfume atelier. {BG} on four legs stands very still, glasses on, eyes closed patiently. Under the front edge of his shell, in the shade, {MG} sleeps curled up with its antennae relaxed. {KK} sits beside them with her hand over her heart, relieved, ears soft.",SU)
scene("u_screen_up",FLASH,["kkito","migae","lachilchin"],"alley_su",f"the green summer alley looking up at a beige apartment building: on its rooftop a white cloth screen stands on poles; at an open 5th-floor window {LC} small and round leans out looking up at the screen. Below, {KK} looks up with one hand shading her eyes. {MG} at her feet.",SU)
scene("u_wall",FLASH,["kkito","ramda","migae"],"alley_su",f"the summer alley. {RM} on a stepladder wipes a big plain wall of a building with a cloth, tail high. {KK} holds the ladder, ears up. {MG} holds the bucket.",SU)
# ---- 영화제 히어로 (Pro) ----
scene("u_fest_full",PRO,["kkito","migae","boneul","ramda","bookgeo","lachilchin"],"fest",f"summer night rooftop film festival: twelve folding chairs facing the glowing white screen, string lights, the alley below. All six exactly once at correct heights: {RM} at the back turning the old projector, {BG} on four legs beside the projector with glasses looking at the lens, {LC} short and round in the front row holding a plate up, {KK} and {BN} tallest sitting side by side in the back row, close together, Kkito's ears up, Boneul with a tiny smile, {MG} sitting on Kkito's lap.")
scene("u_fest_alone",PRO,["kkito","migae"],"alley_n",f"summer night in the alley: a rectangle of projector light shining on a plain building wall, one bench in front of it. {KK} sits alone on the bench looking at the empty light rectangle, ears down. {MG} sits beside her. The shop shutter half closed, dark windows.")
scene("u_fest_bff",PRO,["kkito","boneul","migae"],"fest",f"late night on the rooftop after the festival, chairs empty, the screen dark, string lights still on, the alley below with only a few lit windows. {KK} and {BN}, tallest, lean on the railing side by side looking down at the alley, both laughing, Kkito's ears up and eyes crescent, Boneul with a wide rare smile. {MG} sits on the railing between them with antennae in a heart shape.")
scene("u_fest_book",PRO,["kkito","migae","boneul","ramda","bookgeo","lachilchin"],"fest",f"summer night rooftop festival: on the glowing white screen a simple crayon drawing of the alley is projected (no text). {KK} stands beside the screen holding a picture book open, reading aloud, ears up, cheeks flushed. In the chairs, each exactly once at correct heights: {BN} tallest in the back row smiling, {RM} at the projector, {BG} on four legs with glasses in the aisle, {LC} short and round in the front row. {MG} sits at Kkito's feet.")
scene("u_fest_screen",PRO,["kkito","migae","boneul","ramda","bookgeo","lachilchin"],"fest",f"summer night rooftop festival, the white screen glowing with a plain bright rectangle, chairs full. All six exactly once at correct heights watching the screen from behind at an angle: {BN} tallest, {KK} beside him, {RM} standing by the projector, {BG} on four legs with glasses at the side, {LC} short and round in the front row. {MG} walks in front of the screen casting a huge ant-shaped shadow on it.")
scene("u_fest_window",PRO,["kkito","migae","lachilchin"],"alley_n",f"summer night in the alley: a rectangle of projector light shining on a plain building wall; above, at a lit 5th-floor window {LC} small and round leans out waving. {KK} stands below on a bench waving up with one hand, ears up. {MG} at her feet waving both antennae.")
scene("u_fest_wall",PRO,["kkito","migae","ramda","bookgeo"],"alley_n",f"summer night in the alley: a rectangle of projector light on a plain wall, three benches in front. {RM} operates a small projector on a crate, tail high. {BG} on four legs with glasses sits at the bottom of a stairway watching. {KK} sits on a bench, ears up. {MG} beside her.")
scene("u_w1",FLASH,["kkito","migae"],"alley_su",f"early summer in the green alley, strong sun. {KK} stands under a tree in its shade fanning herself with a paper fan, ears up. {MG} at her feet in the shade looking up at the leaves.",SU)
scene("u_w2",FLASH,["kkito","migae"],"alley_ht",f"peak summer heat in the alley, washed-out light, deep shadows. {KK} lies on the bench in the shade with a wet towel on her forehead, ears hanging down. {MG} lies flat on the ground under the bench.",SU)
# ---- 막간극 2 북거씨 (겨울) ----
WI=" WINTER: snow outside the windows, warm lamp light inside."
scene("b2_open",FLASH,["bookgeo"],"bg_day_perfume_atelier.png",f"morning, the perfume atelier door seen from inside; {BG} on four legs is slowly unlocking the door with a key held in one arm from under his shell, glasses on, calm. Shelves of forty small bottles behind him, one bottle on the windowsill half empty.",WI)
scene("b2_label",FLASH,["bookgeo"],"bg_day_perfume_atelier.png",f"inside the atelier: {BG} on four legs holds a small round bottle up close to his face with one arm from under his shell; its paper label is slightly scorched brown at one corner (no text). Glasses on, looking at it thoughtfully.",WI)
scene("b2_customer",FLASH,["bookgeo","ramda"],"bg_day_perfume_atelier.png",f"inside the atelier: {RM} stands at the counter with a big bright smile but her tail hanging low, holding a coiled string of unlit paper lanterns. {BG} on four legs behind the counter with glasses looks at her tail, holding two small bottles (one orange, one purple) in one arm from under his shell.",WI)
scene("b2_kkito",FLASH,["bookgeo","kkito"],"bg_day_perfume_atelier.png",f"inside the atelier: {KK} has just rushed in, out of breath, ears flat back, both hands on the counter, worried. {BG} on four legs behind the counter, glasses on, looks at her calmly and holds out a paper scent strip with one arm from under his shell.",WI)
scene("b2_migae",FLASH,["bookgeo","migae"],"bg_day_perfume_atelier.png",f"inside the atelier: {BG} on four legs stands still with glasses on and eyes half closed, patient; {MG} is curled up asleep on top of his shell, antennae relaxed. Warm lamp light.",WI)
scene("b2_close",FLASH,["bookgeo"],"bg_day_perfume_atelier.png",f"evening in the atelier: {BG} on four legs writes on a blank label of a new round bottle with a thin pen held in one arm from under his shell, glasses on, very slowly, lamp light, snow at the window. The bottle sits on the windowsill.",WI)
# ---- 막간극 3 할머니 (봄) ----
SPR=" SPRING: pink blossoms outside the windows, soft morning light."
scene("b3_wake",FLASH,["lachilchin"],"bg_day_grandma_room.png",f"early morning in Grandma's small room: {LC}, short and round, sits up on her bed in a nightcap-free plain state, rubbing her knee with one hand, glasses on her head, an old wooden picture frame on the windowsill facing her.",SPR)
scene("b3_snack",FLASH,["lachilchin"],"bg_day_grandma_room.png",f"Grandma's kitchen: {LC}, short and round, stands at the table looking at three things laid out in a row: a bunch of mugwort greens, a small bowl of ginkgo nuts, two sweet potatoes; one hand on her chin, deciding, glasses on her head.",SPR)
scene("b3_window",FLASH,["lachilchin"],"bg_day_grandma_room.png",f"from inside Grandma's room looking out the open 5th-floor window: {LC}, short and round, seen from behind and slightly to the side, leans on the sill looking down at the blossoming alley far below where tiny simple shapes of a running pink figure and a slow tortoise can be seen (very small, no detail).",SPR)
scene("b3_stairs",FLASH,["lachilchin","ramda"],"bg_day_entry.png",f"an apartment stairwell with rubber mats on the steps: {LC}, short and round, holds the handrail coming down one step at a time, glasses on her head. {RM} comes up the stairs toward her, tail high, waving one hand, excited.",SPR)
scene("b3_give",FLASH,["lachilchin","kkito","migae"],"alley_sp",f"the blossoming alley: {LC}, short and round, holds out a plate covered with a cloth toward Kkito with both hands, smiling. {KK} stands in front of her out of breath, ears flat back, reaching for the plate. {MG} already at the plate edge.",SPR)
scene("b3_evening",FLASH,["lachilchin"],"bg_day_grandma_room.png",f"evening in Grandma's room: {LC}, short and round, sits by the open window in dusk light holding an old wooden picture frame in her lap, looking out at the alley below where one small window of a shop is just lighting up warm. Glasses on her head, gentle face.",SPR)
# ---- 막간극 4 미개 (여름 밤) ----
NT=" SUMMER NIGHT: deep blue night, warm lamp lights, a few stars."
scene("b4_night",FLASH,["migae","kkito"],"bg_day_studio.png",f"night in apartment 901: {KK} asleep on the sofa under a thin sheet, a fan turning, ears flopped. {MG} stands on the windowsill of the open window, looking back at Kkito over its shoulder, antennae up, ready to go out.",NT)
scene("b4_alley",FLASH,["migae"],"alley_n",f"the alley at night under a single street lamp, seen from very low, ant height: {MG} stands in the middle of the alley, tiny, antennae up, looking down the long alley of lit and dark windows. No other characters.",NT)
scene("b4_bookgeo",FLASH,["migae","bookgeo"],"bg_day_perfume_atelier.png",f"night, the perfume atelier seen from outside through the window: inside, {BG} on four legs with glasses polishes a bottle held in one arm from under his shell, lamp light. Outside on the sill, {MG} presses both antennae to the glass, seen from behind and to the side.",NT)
scene("b4_trash",FLASH,["migae"],"alley_n",f"night, a small trash collection corner at the alley end with a few bins under a lamp. {MG} stands alone touching the ground with one antenna where a faint round mark of a large container is, antennae forming a heart shape. No other characters.",NT)
scene("b4_roof",FLASH,["migae"],"alley_n",f"night on a small rooftop railing, seen from behind {MG} who sits on the railing, tiny, looking over the whole dark alley with four lit windows in different buildings, antennae in a heart shape. Stars. No other characters.",NT)
scene("b4_tree",FLASH,["migae"],"alley_n",f"night at the very top of a big ginkgo tree, seen from behind {MG} who sits on the highest branch, tiny, looking over the whole dark alley with four lit windows, antennae in a heart shape. Stars. No other characters.",NT)
scene("b4_home",FLASH,["migae","kkito"],"bg_day_studio.png",f"dawn in apartment 901, faint blue light: {KK} asleep on the sofa, ears flopped, a peaceful face. {MG} has just climbed onto her stomach and is settling down, antennae in a heart shape, a tiny petal-like leaf stuck on its head.",NT)
mode=sys.argv[1] if len(sys.argv)>1 else "all"
todo = BGS if mode=="bg" else SHOTS if mode=="scenes" else BGS+SHOTS if mode=="all" else [s for s in BGS+SHOTS if s[0] in set(mode.split(","))]
for id,model,refs,prompt in todo:
    if os.path.exists(f"{OUT}/{id}_0.png"): print("skip",id,flush=True); continue
    missing=[r for r in refs if not os.path.exists(r)]
    if missing: print("MISSING REF",id,missing,flush=True); continue
    open(f"{OUT}/{id}.prompt.txt","w").write(prompt)
    env=dict(os.environ,NB_MODEL=model,NB_AR="3:4",NB_SIZE="1K"); t=time.time()
    for a in range(3):
        r=subprocess.run([sys.executable,f"{SC}/gen.py",f"{OUT}/{id}","1",*refs],stdin=open(f"{OUT}/{id}.prompt.txt"),env=env,capture_output=True,text=True)
        print(id,model.split("-")[2],r.stdout.strip()[-90:],f"({time.time()-t:.0f}s)",flush=True)
        if os.path.exists(f"{OUT}/{id}_0.png"): break
        time.sleep(5)
print("DONE",flush=True)
